# -*- coding: utf-8 -*-
"""auto_Arima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aJ83CLBICL-6kWtgoZHsvF6dK1xcBWDO
"""

! pip install pmdarima

from pmdarima.arima import auto_arima

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

month_review = pd.read_csv('month_review.csv')

month_review

month_review_new = month_review.drop(columns=['Unnamed: 0'])

month_review_new

month_review_new.info()

month_review_new['date']= pd.to_datetime(month_review_new['date'])

month_review_new.set_index('date', inplace=True)

month_review_new.index

month_review_new.plot()

from pmdarima.arima import ADFTest
adf_test = ADFTest(alpha = 0.05)
adf_test.should_diff(month_review_new)

train = month_review_new[:int(0.8*(len(month_review_new)))]
test = month_review_new[int(0.8*(len(month_review_new))):]

plt.plot(train)
plt.plot(test)

arima_model = auto_arima(train, start_p=0, d=1,start_q=0, max_p=5, max_d=5, max_q=5, start_P=0,D=1, start_Q=0,
                         max_P=5, max_D=5, max_Q=5, m=12, seasonal=True,error_action='warn', trace=True,
                         suppress_warnings=True, stepwise= True, random_state=20, n_fit =50)

arima_model.summary()

prediction = pd.DataFrame(arima_model.predict(n_periods=35), index=test.index)
prediction.columns = ['predicted_reviews']
prediction

plt.figure(figsize=(8,5))
plt.plot(train, label="Training")
plt.plot(test, label="Test")
plt.plot(prediction, label="Predicted")
plt.legend(loc ='Left corner')
plt.show()

from sklearn.metrics import r2_score
test['predicted_reviews'] = prediction
r2_score(test['n_reviews'],test['predicted_reviews'])